// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pb/moves.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Team int32

const (
	Team_empty  Team = 0
	Team_yellow Team = 2
	Team_red    Team = 1
)

// Enum value maps for Team.
var (
	Team_name = map[int32]string{
		0: "empty",
		2: "yellow",
		1: "red",
	}
	Team_value = map[string]int32{
		"empty":  0,
		"yellow": 2,
		"red":    1,
	}
)

func (x Team) Enum() *Team {
	p := new(Team)
	*p = x
	return p
}

func (x Team) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Team) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_moves_proto_enumTypes[0].Descriptor()
}

func (Team) Type() protoreflect.EnumType {
	return &file_pb_moves_proto_enumTypes[0]
}

func (x Team) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Team) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Team(num)
	return nil
}

// Deprecated: Use Team.Descriptor instead.
func (Team) EnumDescriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{0}
}

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        *int32                 `protobuf:"varint,1,req,name=game_id,json=gameId" json:"game_id,omitempty"`
	Column        *int32                 `protobuf:"varint,2,req,name=column" json:"column,omitempty"`
	InputTeam     *Team                  `protobuf:"varint,3,req,name=input_team,json=inputTeam,enum=Team" json:"input_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_pb_moves_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_pb_moves_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetGameId() int32 {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return 0
}

func (x *Input) GetColumn() int32 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

func (x *Input) GetInputTeam() Team {
	if x != nil && x.InputTeam != nil {
		return *x.InputTeam
	}
	return Team_empty
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,req,name=field" json:"field,omitempty"`
	Turn          *Team                  `protobuf:"varint,2,req,name=turn,enum=Team" json:"turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_pb_moves_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pb_moves_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *State) GetTurn() Team {
	if x != nil && x.Turn != nil {
		return *x.Turn
	}
	return Team_empty
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_pb_moves_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_pb_moves_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []Team                 `protobuf:"varint,1,rep,name=values,enum=Team" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_pb_moves_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_pb_moves_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetValues() []Team {
	if x != nil {
		return x.Values
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pb_moves_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pb_moves_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{4}
}

type GameIDAndTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Team          *Team                  `protobuf:"varint,2,req,name=team,enum=Team" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameIDAndTeam) Reset() {
	*x = GameIDAndTeam{}
	mi := &file_pb_moves_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameIDAndTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameIDAndTeam) ProtoMessage() {}

func (x *GameIDAndTeam) ProtoReflect() protoreflect.Message {
	mi := &file_pb_moves_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameIDAndTeam.ProtoReflect.Descriptor instead.
func (*GameIDAndTeam) Descriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{5}
}

func (x *GameIDAndTeam) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GameIDAndTeam) GetTeam() Team {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return Team_empty
}

type GameID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameID) Reset() {
	*x = GameID{}
	mi := &file_pb_moves_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameID) ProtoMessage() {}

func (x *GameID) ProtoReflect() protoreflect.Message {
	mi := &file_pb_moves_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameID.ProtoReflect.Descriptor instead.
func (*GameID) Descriptor() ([]byte, []int) {
	return file_pb_moves_proto_rawDescGZIP(), []int{6}
}

func (x *GameID) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

var File_pb_moves_proto protoreflect.FileDescriptor

const file_pb_moves_proto_rawDesc = "" +
	"\n" +
	"\x0epb/moves.proto\"^\n" +
	"\x05Input\x12\x17\n" +
	"\agame_id\x18\x01 \x02(\x05R\x06gameId\x12\x16\n" +
	"\x06column\x18\x02 \x02(\x05R\x06column\x12$\n" +
	"\n" +
	"input_team\x18\x03 \x02(\x0e2\x05.teamR\tinputTeam\"@\n" +
	"\x05State\x12\x1c\n" +
	"\x05field\x18\x01 \x02(\v2\x06.FieldR\x05field\x12\x19\n" +
	"\x04turn\x18\x02 \x02(\x0e2\x05.teamR\x04turn\"!\n" +
	"\x05Field\x12\x18\n" +
	"\x04rows\x18\x01 \x03(\v2\x04.RowR\x04rows\"$\n" +
	"\x03Row\x12\x1d\n" +
	"\x06values\x18\x01 \x03(\x0e2\x05.teamR\x06values\"\a\n" +
	"\x05Empty\":\n" +
	"\rGameIDAndTeam\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id\x12\x19\n" +
	"\x04team\x18\x02 \x02(\x0e2\x05.teamR\x04team\"\x18\n" +
	"\x06GameID\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id*&\n" +
	"\x04team\x12\t\n" +
	"\x05empty\x10\x00\x12\n" +
	"\n" +
	"\x06yellow\x10\x02\x12\a\n" +
	"\x03red\x10\x012\xa7\x01\n" +
	"\bconnect4\x12(\n" +
	"\x10CommunicateState\x12\x06.Input\x1a\x06.State\"\x00(\x010\x01\x12#\n" +
	"\aNewGame\x12\x06.Empty\x1a\x0e.GameIDAndTeam\"\x00\x12%\n" +
	"\bJoinGame\x12\a.GameID\x1a\x0e.GameIDAndTeam\"\x00\x12%\n" +
	"\tLeaveGame\x12\x0e.GameIDAndTeam\x1a\x06.Empty\"\x00B\x12Z\x10connect4-grpc/pb"

var (
	file_pb_moves_proto_rawDescOnce sync.Once
	file_pb_moves_proto_rawDescData []byte
)

func file_pb_moves_proto_rawDescGZIP() []byte {
	file_pb_moves_proto_rawDescOnce.Do(func() {
		file_pb_moves_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_moves_proto_rawDesc), len(file_pb_moves_proto_rawDesc)))
	})
	return file_pb_moves_proto_rawDescData
}

var file_pb_moves_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_moves_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_moves_proto_goTypes = []any{
	(Team)(0),             // 0: team
	(*Input)(nil),         // 1: Input
	(*State)(nil),         // 2: State
	(*Field)(nil),         // 3: Field
	(*Row)(nil),           // 4: Row
	(*Empty)(nil),         // 5: Empty
	(*GameIDAndTeam)(nil), // 6: GameIDAndTeam
	(*GameID)(nil),        // 7: GameID
}
var file_pb_moves_proto_depIdxs = []int32{
	0,  // 0: Input.input_team:type_name -> team
	3,  // 1: State.field:type_name -> Field
	0,  // 2: State.turn:type_name -> team
	4,  // 3: Field.rows:type_name -> Row
	0,  // 4: Row.values:type_name -> team
	0,  // 5: GameIDAndTeam.team:type_name -> team
	1,  // 6: connect4.CommunicateState:input_type -> Input
	5,  // 7: connect4.NewGame:input_type -> Empty
	7,  // 8: connect4.JoinGame:input_type -> GameID
	6,  // 9: connect4.LeaveGame:input_type -> GameIDAndTeam
	2,  // 10: connect4.CommunicateState:output_type -> State
	6,  // 11: connect4.NewGame:output_type -> GameIDAndTeam
	6,  // 12: connect4.JoinGame:output_type -> GameIDAndTeam
	5,  // 13: connect4.LeaveGame:output_type -> Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pb_moves_proto_init() }
func file_pb_moves_proto_init() {
	if File_pb_moves_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_moves_proto_rawDesc), len(file_pb_moves_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_moves_proto_goTypes,
		DependencyIndexes: file_pb_moves_proto_depIdxs,
		EnumInfos:         file_pb_moves_proto_enumTypes,
		MessageInfos:      file_pb_moves_proto_msgTypes,
	}.Build()
	File_pb_moves_proto = out.File
	file_pb_moves_proto_goTypes = nil
	file_pb_moves_proto_depIdxs = nil
}
